// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://awnbengdehcywlkgqhlc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF3bmJlbmdkZWhjeXdsa2dxaGxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjMwMDksImV4cCI6MjA3MzkzOTAwOX0.8BX54SFKJlGRenXyPV1E-Mr6N6LONDUcWcAD-0dnNdE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});